-- --------------------------------------------------------
-- 호스트:                          carborn.site
-- 서버 버전:                        10.3.38-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04
-- 서버 OS:                        debian-linux-gnu
-- HeidiSQL 버전:                  12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- 테이블 S08P22D209.MWS_ACCOUNT 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_ACCOUNT` (
  `ID` varchar(50) NOT NULL,
  `PWD` varchar(200) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `PHONE_NO` varchar(50) NOT NULL,
  `AUTH` tinyint(4) NOT NULL COMMENT '0_일반사용자\r\n1_정비소\r\n2_검사소\r\n3_보험사',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PHONE_NO` (`PHONE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_ACCOUNT_LOGIN_LOG 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_ACCOUNT_LOGIN_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `BROWSER` varchar(50) NOT NULL,
  `IP_ADDR` varchar(50) NOT NULL,
  `OS` varchar(50) NOT NULL,
  `REG_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ACCOUNT_LOGIN_LOG_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_ACCOUNT_LOGIN_LOG_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_BOARD 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_BOARD` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` text NOT NULL,
  `IMG_NM` varchar(200) NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BOARD_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_BOARD_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CAR 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CAR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `WALLET_HASH` varchar(200) NOT NULL COMMENT '자동차 지갑 해시',
  `MAKER` varchar(50) NOT NULL COMMENT '제조사',
  `MODEL_NM` varchar(200) NOT NULL COMMENT '모델명',
  `MODEL_YEAR` varchar(50) NOT NULL COMMENT '모델연식',
  `REG_NM` varchar(50) NOT NULL COMMENT '차량등록번호',
  `VIN` varchar(200) NOT NULL COMMENT '차대번호',
  `MILEAGE` int(11) NOT NULL COMMENT '주행거리',
  `CONTRACT_HASH` varchar(200) NOT NULL COMMENT '컨트랙트 해시',
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `VIN` (`VIN`),
  UNIQUE KEY `REG_NUM` (`REG_NM`) USING BTREE,
  KEY `FK_CAR_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_CAR_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CAR_IMG 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CAR_IMG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAR_ID` int(11) NOT NULL,
  `IMG_NM` varchar(200) NOT NULL,
  `CONTRACT_HASH` varchar(200) NOT NULL COMMENT '컨트랙트 해시',
  `REG_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CAR_IMG_CAR_ID` (`CAR_ID`),
  CONSTRAINT `FK_CAR_IMG_CAR_ID` FOREIGN KEY (`CAR_ID`) REFERENCES `MWS_CAR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CAR_INSURANCE_HISTORY 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CAR_INSURANCE_HISTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSURANCE_COM_ID` int(11) NOT NULL,
  `CAR_ID` int(11) NOT NULL,
  `CAR_VIN` varchar(200) NOT NULL COMMENT '차대번호',
  `CATEGORY` varchar(200) NOT NULL COMMENT '차량손상 분류',
  `CONTENT` text NOT NULL COMMENT '보험처리 내역',
  `INSURANCE_IMG_NM` varchar(200) NOT NULL COMMENT '보험내역 이미지',
  `INSURANCE_DT` datetime NOT NULL COMMENT '보험처리 일시',
  `CONTRACT_HASH` varchar(200) NOT NULL COMMENT '컨트랙트 해시',
  `METADATA_URI` varchar(200) NOT NULL,
  `REG_DT` datetime NOT NULL COMMENT '등록일시',
  PRIMARY KEY (`ID`),
  KEY `FK_CAR_INSURANCE_HISTORY_CAR_ID` (`CAR_ID`),
  KEY `FK_CAR_INSURANCE_HISTORY_INSURANCE_COM_ID` (`INSURANCE_COM_ID`),
  CONSTRAINT `FK_CAR_INSURANCE_HISTORY_CAR_ID` FOREIGN KEY (`CAR_ID`) REFERENCES `MWS_CAR` (`ID`),
  CONSTRAINT `FK_CAR_INSURANCE_HISTORY_INSURANCE_COM_ID` FOREIGN KEY (`INSURANCE_COM_ID`) REFERENCES `MWS_INSURANCE_COM` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='보험 이력';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CAR_SALE 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CAR_SALE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `CAR_ID` int(11) NOT NULL,
  `CONTENT` text NOT NULL,
  `PRICE` int(11) NOT NULL,
  `SALE_STATUS` tinyint(4) NOT NULL COMMENT '0 판매중\r\n1 판매완료\r\n2 판매취소',
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CAR_SALE_ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `FK_CAR_SALE_CAR_ID` (`CAR_ID`),
  CONSTRAINT `FK_CAR_SALE_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_CAR_SALE_CAR_ID` FOREIGN KEY (`CAR_ID`) REFERENCES `MWS_CAR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량 판매';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CAR_SALE_BOOK 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CAR_SALE_BOOK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `CAR_SALE_ID` int(11) NOT NULL,
  `BOOK_STATUS` tinyint(4) NOT NULL COMMENT '0 예약 중 \r\n1구매완료\r\n2 예약취소',
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CAR_SALE_BOOJ_ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `FK_CAR_SALE_BOOK_CAR_SALE_ID` (`CAR_SALE_ID`),
  CONSTRAINT `FK_CAR_SALE_BOOJ_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_CAR_SALE_BOOK_CAR_SALE_ID` FOREIGN KEY (`CAR_SALE_ID`) REFERENCES `MWS_CAR_SALE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량 구매 예약';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CAR_TRADE 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CAR_TRADE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAR_ID` int(11) NOT NULL,
  `BUYER_ID` varchar(50) NOT NULL,
  `SELLER_ID` varchar(50) NOT NULL,
  `PRICE` int(11) NOT NULL,
  `CONTRACT_HASH` varchar(200) NOT NULL,
  `METADATA_URI` varchar(200) NOT NULL,
  `REG_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CAR_TRADE_CAR_ID` (`CAR_ID`),
  KEY `FK_CAR_TRADE_ACCOUNT_ID_BUYER` (`BUYER_ID`),
  KEY `FK_CAR_TRADE_ACCOUNT_ID_SELLER` (`SELLER_ID`),
  CONSTRAINT `FK_CAR_TRADE_ACCOUNT_ID_BUYER` FOREIGN KEY (`BUYER_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_CAR_TRADE_ACCOUNT_ID_SELLER` FOREIGN KEY (`SELLER_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_CAR_TRADE_CAR_ID` FOREIGN KEY (`CAR_ID`) REFERENCES `MWS_CAR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CAR_VRC 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CAR_VRC` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAR_ID` int(11) NOT NULL,
  `IMG_NM` varchar(200) NOT NULL,
  `CONTRACT_HASH` varchar(200) NOT NULL COMMENT '컨트랙트 해시',
  `REG_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CAR_CBR_CAR_ID` (`CAR_ID`),
  CONSTRAINT `FK_CAR_CBR_CAR_ID` FOREIGN KEY (`CAR_ID`) REFERENCES `MWS_CAR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량등록증';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_CBR 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_CBR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(11) NOT NULL,
  `IMG_NM` varchar(200) NOT NULL,
  `REG_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CBR_COMPANY_ID` (`COMPANY_ID`),
  CONSTRAINT `FK_CBR_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `MWS_COMPANY` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='사업자등록증';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_COMMUNITY 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_COMMUNITY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` text NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `VIEWS` int(11) NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COMMUNITY_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_COMMUNITY_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_COMMUNITY_REVIEW 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_COMMUNITY_REVIEW` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMMUNITY_ID` int(11) NOT NULL,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COMMUNITY_REVIEW_ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `FK_COMMUNITY_REVIEW_COMMUNITY_ID` (`COMMUNITY_ID`),
  CONSTRAINT `FK_COMMUNITY_REVIEW_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_COMMUNITY_REVIEW_COMMUNITY_ID` FOREIGN KEY (`COMMUNITY_ID`) REFERENCES `MWS_COMMUNITY` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_COMPANY 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_COMPANY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `BRN` varchar(50) NOT NULL COMMENT '사업자 등록번호',
  PRIMARY KEY (`ID`),
  KEY `FK_COMPANY_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_COMPANY_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_INSPECTOR 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_INSPECTOR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `ADDRESS` varchar(200) NOT NULL,
  `LAT` double NOT NULL,
  `LNG` double NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_INSPECTOR_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_INSPECTOR_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량 검사소';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_INSPECTOR_REVIEW 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_INSPECTOR_REVIEW` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSPECT_RESULT_ID` int(11) NOT NULL,
  `INSPECTOR_ID` int(11) NOT NULL,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `POINT` int(11) NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_INSPECTOR_REVIEW_ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `FK_INSPECTOR_REVIEW_INSPECTOR_ID` (`INSPECTOR_ID`),
  KEY `FK_INSPECTOR_REVIEW_INSPECT_RESULT_ID` (`INSPECT_RESULT_ID`),
  CONSTRAINT `FK_INSPECTOR_REVIEW_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_INSPECTOR_REVIEW_INSPECTOR_ID` FOREIGN KEY (`INSPECTOR_ID`) REFERENCES `MWS_INSPECTOR` (`ID`),
  CONSTRAINT `FK_INSPECTOR_REVIEW_INSPECT_RESULT_ID` FOREIGN KEY (`INSPECT_RESULT_ID`) REFERENCES `MWS_INSPECT_RESULT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_INSPECT_BOOK 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_INSPECT_BOOK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAR_ID` int(11) NOT NULL,
  `INSPECTOR_ID` int(11) NOT NULL,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `BOOK_STATUS` tinyint(4) NOT NULL COMMENT '0 : 예약 대기, 1 : 검수 완료, 2 : 예약 취소',
  `BOOK_DT` date NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_INSPECT_ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `FK_INSPECT_CAR_ID` (`CAR_ID`),
  KEY `FK_INSPECT_INSPECTOR_ID` (`INSPECTOR_ID`),
  CONSTRAINT `FK_INSPECT_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_INSPECT_CAR_ID` FOREIGN KEY (`CAR_ID`) REFERENCES `MWS_CAR` (`ID`),
  CONSTRAINT `FK_INSPECT_INSPECTOR_ID` FOREIGN KEY (`INSPECTOR_ID`) REFERENCES `MWS_INSPECTOR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량검수 예약';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_INSPECT_RESULT 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_INSPECT_RESULT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSPECT_BOOK_ID` int(11) NOT NULL,
  `CONTENT` text NOT NULL,
  `MILEAGE` int(11) NOT NULL,
  `BEFORE_IMG_NM` varchar(200) NOT NULL,
  `AFTER_IMG_NM` varchar(200) NOT NULL,
  `RECEIPT_IMG_NM` varchar(200) NOT NULL,
  `INSPECT_PRICE` int(11) NOT NULL,
  `INSPECT_DT` datetime NOT NULL,
  `CONTRACT_HASH` varchar(200) NOT NULL COMMENT '컨트랙트 해시',
  `METADATA_URI` varchar(200) NOT NULL,
  `REG_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INSPECT_BOOK_ID` (`INSPECT_BOOK_ID`),
  KEY `FK_INSPECT_RESULT_CAR_ID` (`INSPECT_BOOK_ID`),
  CONSTRAINT `FK_INSPECT_RESULT_INSPECT_BOOK_ID` FOREIGN KEY (`INSPECT_BOOK_ID`) REFERENCES `MWS_INSPECT_BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량검수 결과';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_INSURANCE_COM 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_INSURANCE_COM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_INSURANCE_COM_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_INSURANCE_COM_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='보험사';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_REPAIR_BOOK 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_REPAIR_BOOK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAR_ID` int(11) NOT NULL,
  `REPAIR_SHOP_ID` int(11) NOT NULL,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `BOOK_STATUS` tinyint(4) NOT NULL COMMENT '예약 상태',
  `BOOK_DT` date NOT NULL COMMENT '차량수리 예약일시',
  `REG_DT` datetime NOT NULL COMMENT '예약 등록일시',
  `UPT_DT` datetime NOT NULL COMMENT '예약 수정일시',
  `STATUS` tinyint(1) NOT NULL COMMENT '예약글 상태',
  PRIMARY KEY (`ID`),
  KEY `FK_REPAIR_BOOK_ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `FK_REPAIR_BOOK_CAR_ID` (`CAR_ID`),
  KEY `FK_REPAIR_BOOK_REPAIR_SHOP_ID` (`REPAIR_SHOP_ID`),
  CONSTRAINT `FK_REPAIR_BOOK_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_REPAIR_BOOK_CAR_ID` FOREIGN KEY (`CAR_ID`) REFERENCES `MWS_CAR` (`ID`),
  CONSTRAINT `FK_REPAIR_BOOK_REPAIR_SHOP_ID` FOREIGN KEY (`REPAIR_SHOP_ID`) REFERENCES `MWS_REPAIR_SHOP` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량 정비 예약';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_REPAIR_RESULT 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_REPAIR_RESULT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REPAIR_BOOK_ID` int(11) NOT NULL,
  `CONTENT` text NOT NULL,
  `MILEAGE` int(11) NOT NULL,
  `BEFORE_IMG_NM` varchar(200) NOT NULL COMMENT '차량수리 전 이미지',
  `AFTER_IMG_NM` varchar(200) NOT NULL COMMENT '차량수리 후 이미지',
  `RECEIPT_IMG_NM` varchar(200) NOT NULL COMMENT '견적서 이미지',
  `REPAIR_PRICE` int(11) NOT NULL,
  `REPAIR_DT` datetime NOT NULL,
  `CONTRACT_HASH` varchar(200) NOT NULL COMMENT '컨트랙트 해시',
  `METADATA_URI` varchar(200) NOT NULL,
  `REG_DT` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `REPAIR_BOOK_ID` (`REPAIR_BOOK_ID`),
  KEY `FK_REPAIR_RESULT_REPAIR_BOOK_ID` (`REPAIR_BOOK_ID`),
  CONSTRAINT `FK_REPAIR_RESULT_REPAIR_BOOK_ID` FOREIGN KEY (`REPAIR_BOOK_ID`) REFERENCES `MWS_REPAIR_BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='차량수리 결과';

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_REPAIR_SHOP 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_REPAIR_SHOP` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `ADDRESS` varchar(200) NOT NULL,
  `LAT` double NOT NULL,
  `LNG` double NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_REPAIR_SHOP_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_REPAIR_SHOP_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_REPAIR_SHOP_REVIEW 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_REPAIR_SHOP_REVIEW` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REPAIR_RESULT_ID` int(11) NOT NULL,
  `REPAIR_SHOP_ID` int(11) NOT NULL,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `POINT` int(11) NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_REPAIR_SHOP_REVIEW_ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `FK_REPAIR_SHOP_REVIEW_REPAIR_SHOP_ID` (`REPAIR_SHOP_ID`),
  KEY `FK_REPAIR_SHOP_REVIEW_REPAIR_RESULT_ID` (`REPAIR_RESULT_ID`),
  CONSTRAINT `FK_REPAIR_SHOP_REVIEW_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`),
  CONSTRAINT `FK_REPAIR_SHOP_REVIEW_REPAIR_RESULT_ID` FOREIGN KEY (`REPAIR_RESULT_ID`) REFERENCES `MWS_REPAIR_RESULT` (`ID`),
  CONSTRAINT `FK_REPAIR_SHOP_REVIEW_REPAIR_SHOP_ID` FOREIGN KEY (`REPAIR_SHOP_ID`) REFERENCES `MWS_REPAIR_SHOP` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_SELF_REPAIR 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_SELF_REPAIR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(200) NOT NULL,
  `CONTENT` text NOT NULL,
  `REG_DT` datetime NOT NULL,
  `UPT_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_SMS_AUTH 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_SMS_AUTH` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PHONE_NM` varchar(50) NOT NULL,
  `AUTH_NM` varchar(50) NOT NULL,
  `REG_DT` datetime NOT NULL,
  `EXP_DT` datetime NOT NULL,
  `STATUS` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_AUTH_PHONENUM` (`PHONE_NM`) USING BTREE,
  KEY `IDX_AUTH_PHONENUM_EXPDT_STATUS` (`PHONE_NM`,`EXP_DT`,`STATUS`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_TERMS 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_TERMS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

-- 테이블 S08P22D209.MWS_USER 구조 내보내기
CREATE TABLE IF NOT EXISTS `MWS_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` varchar(50) NOT NULL,
  `BIRTH` date NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_USER_ACCOUNT_ID` (`ACCOUNT_ID`),
  CONSTRAINT `FK_USER_ACCOUNT_ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `MWS_ACCOUNT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 내보낼 데이터가 선택되어 있지 않습니다.

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
